---
apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    env: dev

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-res
  namespace: dev
spec:
  hard:
    requests.cpu: 10m
    requests.memory: 500Mi
    limits.cpu: 50m
    limits.memory: 1Gi
    pods: "3"
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythoy-deployment
  namespace: dev
spec:
  replicas: 4
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
        - name: python-app
          image: prasad315/flask-app
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: 3m
              memory: 150Mi
            limits:
              cpu: 10m
              memory: 300Mi


# this deployment will create only 3 replicas as you set pods limit is 3 in resource quota
# i thisway you can limit the entire resource for namesapce and pods too
