# ReplicaSet Example
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: web-replica-set
  namespace: default
spec:
  # Number of replicas to maintain
  replicas: 3
  # Selector to identify pods managed by this ReplicaSet
  selector:
    matchLabels:
      app: web-app
      tier: frontend
  # Pod template specification
  template:
    metadata:
      labels:
        app: web-app
        tier: frontend
        version: v1
    spec:
      containers:
      - name: web
        image: nginx:1.14
        ports:
        - containerPort: 80
      
